# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/electricity.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/electricity.proto\"\x16\n\x14GetMeterUsageRequest\"9\n\x13\x45lectricityResponse\x12\"\n\x07records\x18\x01 \x03(\x0b\x32\x11.MeterUsageRecord\"4\n\x10MeterUsageRecord\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\r\n\x05usage\x18\x02 \x01(\x01\x32W\n\x12\x45lectricityService\x12\x41\n\x12GetElectricityData\x12\x15.GetMeterUsageRequest\x1a\x14.ElectricityResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.electricity_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETMETERUSAGEREQUEST._serialized_start=27
  _GETMETERUSAGEREQUEST._serialized_end=49
  _ELECTRICITYRESPONSE._serialized_start=51
  _ELECTRICITYRESPONSE._serialized_end=108
  _METERUSAGERECORD._serialized_start=110
  _METERUSAGERECORD._serialized_end=162
  _ELECTRICITYSERVICE._serialized_start=164
  _ELECTRICITYSERVICE._serialized_end=251
# @@protoc_insertion_point(module_scope)
